-- Migration 0010: Seed completo de todas as lojas parceiras
-- Adiciona as lojas que faltavam além das 8 originais

INSERT OR IGNORE INTO stores (slug, name, logo_url, affiliate_network, checkout_pattern, deeplink_base, commission_rate, is_active) VALUES

-- ── Já existentes (INSERT OR IGNORE não duplica) ──────────────────────
('amazon',      'Amazon',           'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',                                                        'amazon-pa-api', 'https://www.amazon.com.br/gp/aws/cart/add.html?ASIN.1={ID}&Quantity.1=1', 'https://www.amazon.com.br/dp/{ID}', 8.0, 1),
('magalu',      'Magazine Luiza',   'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Magazine_Luiza_logo.svg/320px-Magazine_Luiza_logo.svg.png',         'magalu-api',    'https://www.magazineluiza.com.br/carrinho/adicionar/{ID}/', 'https://www.magazineluiza.com.br/produto/{ID}/', 5.0, 1),
('mercadolivre','Mercado Livre',    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mercado_Libre_logo.svg/320px-Mercado_Libre_logo.svg.png',           'meli-api',      'https://www.mercadolivre.com.br/checkout/buy?item_id={ID}&quantity=1', 'https://produto.mercadolivre.com.br/{ID}', 3.0, 1),
('shopee',      'Shopee',           'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Shopee.svg/320px-Shopee.svg.png',                                   'shopee-api',    'https://shopee.com.br/product/{ID}', 'https://shopee.com.br/product/{ID}', 6.0, 1),
('americanas',  'Americanas',       'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Americanas_logo.svg/320px-Americanas_logo.svg.png',                 'awin',          'https://www.americanas.com.br/produto/{ID}', 'https://www.americanas.com.br/produto/{ID}', 4.5, 1),
('casasbahia',  'Casas Bahia',      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/CasasBahia_logo.svg/320px-CasasBahia_logo.svg.png',                 'awin',          'https://www.casasbahia.com.br/produto/{ID}/carrinho', 'https://www.casasbahia.com.br/produto/{ID}', 4.0, 1),
('submarino',   'Submarino',        'https://logodownload.org/wp-content/uploads/2018/04/submarino-logo.png',                                                      'awin',          'https://www.submarino.com.br/produto/{ID}', 'https://www.submarino.com.br/produto/{ID}', 4.5, 1),
('aliexpress',  'AliExpress',       'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Aliexpress_logo.svg/320px-Aliexpress_logo.svg.png',                 'aliexpress-portals', 'https://www.aliexpress.com/item/{ID}.html', 'https://www.aliexpress.com/item/{ID}.html', 7.0, 1),

-- ── Novas lojas ───────────────────────────────────────────────────────
('shein',       'Shein',            'https://img.ltwebstatic.com/images3_pi/2021/09/09/163116524781ac3c96c8fe8b5d0ab65ef7e09b65f8_thumbnail_900x.jpg',             'shein-api',     'https://br.shein.com/product/{ID}.html', 'https://br.shein.com/product/{ID}.html', 15.0, 1),
('dafiti',      'Dafiti',           'https://www.dafiti.com.br/static/version1/frontend/dafiti/br/default/images/svg/logo.svg',                                    'awin',          'https://www.dafiti.com.br/produto/{ID}.html', 'https://www.dafiti.com.br/produto/{ID}.html', 8.0, 1),
('netshoes',    'Netshoes',         'https://logo.clearbit.com/netshoes.com.br',                                                                                   'awin',          'https://www.netshoes.com.br/produto/{ID}', 'https://www.netshoes.com.br/produto/{ID}', 7.0, 1),
('zattini',     'Zattini',          'https://logo.clearbit.com/zattini.com.br',                                                                                    'awin',          'https://www.zattini.com.br/produto/{ID}', 'https://www.zattini.com.br/produto/{ID}', 7.0, 1),
('centauro',    'Centauro',         'https://logo.clearbit.com/centauro.com.br',                                                                                   'lomadee',       'https://www.centauro.com.br/produto/{ID}', 'https://www.centauro.com.br/produto/{ID}', 6.0, 1),
('kabum',       'KaBuM!',           'https://logo.clearbit.com/kabum.com.br',                                                                                      'lomadee',       'https://www.kabum.com.br/produto/{ID}', 'https://www.kabum.com.br/produto/{ID}', 5.0, 1),
('pichau',      'Pichau',           'https://logo.clearbit.com/pichau.com.br',                                                                                     'awin',          'https://www.pichau.com.br/produto/{ID}', 'https://www.pichau.com.br/produto/{ID}', 4.0, 1),
('terabyte',    'Terabyte',         'https://logo.clearbit.com/terabyteshop.com.br',                                                                               'awin',          'https://www.terabyteshop.com.br/produto/{ID}', 'https://www.terabyteshop.com.br/produto/{ID}', 4.0, 1),
('pontofrio',   'Ponto Frio',       'https://logo.clearbit.com/pontofrio.com.br',                                                                                  'awin',          'https://www.pontofrio.com.br/produto/{ID}', 'https://www.pontofrio.com.br/produto/{ID}', 4.0, 1),
('extra',       'Extra',            'https://logo.clearbit.com/extra.com.br',                                                                                      'awin',          'https://www.extra.com.br/produto/{ID}', 'https://www.extra.com.br/produto/{ID}', 4.0, 1),
('carrefour',   'Carrefour',        'https://logo.clearbit.com/carrefour.com.br',                                                                                  'awin',          'https://www.carrefour.com.br/produto/{ID}', 'https://www.carrefour.com.br/produto/{ID}', 3.5, 1),
('fastshop',    'Fast Shop',        'https://logo.clearbit.com/fastshop.com.br',                                                                                   'awin',          'https://www.fastshop.com.br/web/c/p/produto/{ID}', 'https://www.fastshop.com.br/web/c/p/produto/{ID}', 4.0, 1),
('renner',      'Renner',           'https://logo.clearbit.com/lojasrenner.com.br',                                                                                'lomadee',       'https://www.lojasrenner.com.br/produto/{ID}', 'https://www.lojasrenner.com.br/produto/{ID}', 8.0, 1),
('riachuelo',   'Riachuelo',        'https://logo.clearbit.com/riachuelo.com.br',                                                                                  'lomadee',       'https://www.riachuelo.com.br/produto/{ID}', 'https://www.riachuelo.com.br/produto/{ID}', 7.0, 1),
('havan',       'Havan',            'https://logo.clearbit.com/havan.com.br',                                                                                      'awin',          'https://www.havan.com.br/produto/{ID}', 'https://www.havan.com.br/produto/{ID}', 5.0, 1),
('leroy',       'Leroy Merlin',     'https://logo.clearbit.com/leroymerlin.com.br',                                                                                'lomadee',       'https://www.leroymerlin.com.br/produto/{ID}', 'https://www.leroymerlin.com.br/produto/{ID}', 4.0, 1),
('madeiramadeira','MadeiraMadeira', 'https://logo.clearbit.com/madeiramadeira.com.br',                                                                             'lomadee',       'https://www.madeiramadeira.com.br/produto/{ID}', 'https://www.madeiramadeira.com.br/produto/{ID}', 6.0, 1),
('tok_stok',    'Tok&Stok',         'https://logo.clearbit.com/tokstok.com.br',                                                                                    'awin',          'https://www.tokstok.com.br/produto/{ID}', 'https://www.tokstok.com.br/produto/{ID}', 5.0, 1),
('samsung',     'Samsung',          'https://logo.clearbit.com/samsung.com/br',                                                                                    'awin',          'https://www.samsung.com/br/produto/{ID}/', 'https://www.samsung.com/br/produto/{ID}/', 3.0, 1),
('apple',       'Apple',            'https://logo.clearbit.com/apple.com/br',                                                                                      'awin',          'https://www.apple.com/br/shop/{ID}', 'https://www.apple.com/br/shop/{ID}', 2.0, 1),
('dell',        'Dell',             'https://logo.clearbit.com/dell.com/pt-br',                                                                                    'awin',          'https://www.dell.com/pt-br/shop/{ID}', 'https://www.dell.com/pt-br/shop/{ID}', 3.0, 1),
('lenovo',      'Lenovo',           'https://logo.clearbit.com/lenovo.com/br',                                                                                     'awin',          'https://www.lenovo.com/br/pt/produto/{ID}', 'https://www.lenovo.com/br/pt/produto/{ID}', 3.5, 1),
('hotmart',     'Hotmart',          'https://logo.clearbit.com/hotmart.com',                                                                                       'hotmart-api',   'https://pay.hotmart.com/{ID}', 'https://hotmart.com/produto/{ID}', 40.0, 1),
('eduzz',       'Eduzz',            'https://logo.clearbit.com/eduzz.com',                                                                                         'eduzz-api',     'https://eduzz.com/produto/{ID}', 'https://eduzz.com/produto/{ID}', 40.0, 1),
('monetizze',   'Monetizze',        'https://logo.clearbit.com/monetizze.com.br',                                                                                  'monetizze-api', 'https://monetizze.com.br/checkout/{ID}', 'https://monetizze.com.br/checkout/{ID}', 35.0, 1);
